"""Add is_public to Gallery

Revision ID: f2a0906e0636
Revises: 7b4dbdcd6b3c
Create Date: 2025-07-19 08:52:50.304231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a0906e0636'
down_revision = '7b4dbdcd6b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
